name: depauth
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.15
  multi_split_view: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  widget_arrows: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
