name: depauth
publish_to: none
version: 1.1.0+3

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  assorted_layout_widgets: ^8.0.4
  cross_file: ^0.3.3+6
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  intl: any
  jovial_svg: ^1.1.15
  multi_split_view: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  sanitize_filename: ^1.0.5
  share_plus: ^7.2.1
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  url_launcher: ^6.2.1
  widget_arrows: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.6

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#191c1e"

flutter_launcher_icons:
  adaptive_icon_background: "#004d64"
  adaptive_icon_foreground: misc/square.png
  android: true
  image_path: misc/square.png

msix_config:
  display_name: DepAuth
  identity_name: 42626NazarVinnichuk.DepAuth
  logo_path: misc/square.png
  msix_version: 1.1.0.0
  publisher: CN=380FADA1-3D36-4086-BD01-792DE16F16EE
  publisher_display_name: Nazar Vinnichuk
  store: true
  trim_logo: false
  windows_build_args: --obfuscate --split-debug-info=debug-info
