name: depauth
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  intl: any
  multi_split_view: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  sanitize_filename: ^1.0.5
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  widget_arrows: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#191c1e"

flutter_launcher_icons:
  android: true
  image_path: misc/square.png
  adaptive_icon_background: "#004d64"
  adaptive_icon_foreground: misc/square.png
