name: Release

on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cedvdb/action-flutter-build-android@v1
        with:
          keystore-base64: "${{ secrets.ANDROID_RELEASE_KEY }}"
          keystore-password: "${{ secrets.ANDROID_RELEASE_PASSWORD }}"
          build-cmd: flutter build appbundle
          working-directory: ./
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
